In [146]:
import folium
import pandas as pd
import datetime as dt
from IPython.display import Audio
import plotly.express as px

In [25]:
df = pd.read_csv("merged_output.csv")

Functions for the process

In [75]:
#Playing music
def play_sound():
    return Audio('abc.mp3', autoplay=True)

In [123]:
#to_epoch

def to_epoch(s):
    year = int(s[0:4])
    month = int(s[5:7])
    date = int(s[8:10])
    hour = int(s[11:13])
    minute = int(s[14:16])
    second = int(s[17:19])
    
    return dt.datetime(year,month,date,hour,minute,second).timestamp()

In [65]:
def month(s):
    return int(s[5:7])

def date(s):
    return int(s[8:10])

In [127]:
min_epoch = min(df["start_time_epoch"])
print(min_epoch)
def epoch_time_minus(s):
    return s-min_epoch

1640975405

In [26]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,C2F7DD78E82EC875,electric_bike,2022-01-13 11:59:47,2022-01-13 12:02:44,Glenwood Ave & Touhy Ave,525,Clark St & Touhy Ave,RP-007,42.012800,-87.665906,42.012560,-87.674367,casual
1,A6CF8980A652D272,electric_bike,2022-01-10 08:41:56,2022-01-10 08:46:17,Glenwood Ave & Touhy Ave,525,Clark St & Touhy Ave,RP-007,42.012763,-87.665967,42.012560,-87.674367,casual
2,BD0F91DFF741C66D,classic_bike,2022-01-25 04:53:40,2022-01-25 04:58:01,Sheffield Ave & Fullerton Ave,TA1306000016,Greenview Ave & Fullerton Ave,TA1307000001,41.925602,-87.653708,41.925330,-87.665800,member
3,CBB80ED419105406,classic_bike,2022-01-04 00:18:04,2022-01-04 00:33:00,Clark St & Bryn Mawr Ave,KA1504000151,Paulina St & Montrose Ave,TA1309000021,41.983593,-87.669154,41.961507,-87.671387,casual
4,DDC963BFDDA51EEA,classic_bike,2022-01-20 01:31:10,2022-01-20 01:37:12,Michigan Ave & Jackson Blvd,TA1309000002,State St & Randolph St,TA1305000029,41.877850,-87.624080,41.884621,-87.627834,member

In [41]:
df.loc[df["start_station_id"].isna() , "start_station_id"]= 0
df.loc[df["end_station_id"].isna() , "end_station_id"]= 0
df.loc[df["end_station_name"].isna() , "end_station_name"]= "unavailable"
df.loc[df["start_station_name"].isna() , "start_station_name"]= "unavailable"
df.loc[df["start_lat"].isna() , "start_lat"]= 0
df.loc[df["start_lng"].isna() , "start_lng"]= 0
df.loc[df["end_lat"].isna() , "end_lat"]= 0
df.loc[df["end_lng"].isna() , "end_lng"]= 0

In [117]:
df["start_time_epoch"] = df["started_at"].apply(to_epoch)
df["end_time_epoch"] = df["ended_at"].apply(to_epoch)

In [118]:
df["month"] = df["started_at"].apply(month)
df["date"] = df["started_at"].apply(date)

In [119]:
df = df.sort_values(by=['start_time_epoch'])

In [128]:
df["start_epoch"] = df["start_time_epoch"].apply(epoch_time_minus)
df["end_epoch"] = df["end_time_epoch"].apply(epoch_time_minus)

In [129]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,start_time_epoch,end_time_epoch,month,date,start_epoch,end_epoch
73479,98D355D9A9852BE9,classic_bike,2022-01-01 00:00:05,2022-01-01 00:01:48,Michigan Ave & 8th St,623,Michigan Ave & 8th St,623,41.872773,-87.623981,41.872773,-87.623981,casual,1.640975e+09,1.640976e+09,1,1,0.0,103.0
68510,04706CA7F5BD25EE,electric_bike,2022-01-01 00:01:00,2022-01-01 00:04:39,Broadway & Waveland Ave,13325,Broadway & Barry Ave,13137,41.949073,-87.648633,41.937582,-87.644098,casual,1.640975e+09,1.640976e+09,1,1,55.0,274.0
64490,42178E850B92597A,electric_bike,2022-01-01 00:01:16,2022-01-01 00:32:14,Clark St & Ida B Wells Dr,TA1305000009,Clark St & Ida B Wells Dr,TA1305000009,41.875919,-87.631194,41.875933,-87.630585,casual,1.640975e+09,1.640977e+09,1,1,71.0,1929.0
73485,6B93C46E8F5B114C,classic_bike,2022-01-01 00:02:14,2022-01-01 00:31:07,Michigan Ave & 8th St,623,Michigan Ave & 8th St,623,41.872773,-87.623981,41.872773,-87.623981,casual,1.640976e+09,1.640977e+09,1,1,129.0,1862.0
73478,466943353EAC8022,classic_bike,2022-01-01 00:02:35,2022-01-01 00:31:04,Michigan Ave & 8th St,623,Michigan Ave & 8th St,623,41.872773,-87.623981,41.872773,-87.623981,casual,1.640976e+09,1.640977e+09,1,1,150.0,1859.0

In [144]:
df["ride_time"] = round((df["end_epoch"] - df["start_epoch"])/60 , 3)

C:\Users\rakes\AppData\Local\Temp\ipykernel_13952\355004667.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ride_time"] = round((df["end_epoch"] - df["start_epoch"])/60 , 3)

In [134]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,start_time_epoch,end_time_epoch,month,date,start_epoch,end_epoch,ride_time
73479,98D355D9A9852BE9,classic_bike,2022-01-01 00:00:05,2022-01-01 00:01:48,Michigan Ave & 8th St,623,Michigan Ave & 8th St,623,41.872773,-87.623981,41.872773,-87.623981,casual,1.640975e+09,1.640976e+09,1,1,0.0,103.0,1.717
68510,04706CA7F5BD25EE,electric_bike,2022-01-01 00:01:00,2022-01-01 00:04:39,Broadway & Waveland Ave,13325,Broadway & Barry Ave,13137,41.949073,-87.648633,41.937582,-87.644098,casual,1.640975e+09,1.640976e+09,1,1,55.0,274.0,3.650
64490,42178E850B92597A,electric_bike,2022-01-01 00:01:16,2022-01-01 00:32:14,Clark St & Ida B Wells Dr,TA1305000009,Clark St & Ida B Wells Dr,TA1305000009,41.875919,-87.631194,41.875933,-87.630585,casual,1.640975e+09,1.640977e+09,1,1,71.0,1929.0,30.967
73485,6B93C46E8F5B114C,classic_bike,2022-01-01 00:02:14,2022-01-01 00:31:07,Michigan Ave & 8th St,623,Michigan Ave & 8th St,623,41.872773,-87.623981,41.872773,-87.623981,casual,1.640976e+09,1.640977e+09,1,1,129.0,1862.0,28.883
73478,466943353EAC8022,classic_bike,2022-01-01 00:02:35,2022-01-01 00:31:04,Michigan Ave & 8th St,623,Michigan Ave & 8th St,623,41.872773,-87.623981,41.872773,-87.623981,casual,1.640976e+09,1.640977e+09,1,1,150.0,1859.0,28.483

In [139]:
df.loc[df["ride_time"]<0]

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,start_time_epoch,end_time_epoch,month,date,start_epoch,end_epoch,ride_time
403591,2D97E3C98E165D80,classic_bike,2022-03-05 11:00:57,2022-03-05 10:55:01,DuSable Lake Shore Dr & Wellington Ave,TA1307000041,DuSable Lake Shore Dr & Wellington Ave,TA1307000041,41.936688,-87.636829,41.936688,-87.636829,casual,1.646458e+09,1.646458e+09,3,5,5482852.0,5482496.0,-5.933
406768,7407049C5D89A13D,electric_bike,2022-03-05 11:38:04,2022-03-05 11:37:57,Sheffield Ave & Wellington Ave,TA1307000052,Sheffield Ave & Wellington Ave,TA1307000052,41.936313,-87.652522,41.936253,-87.652662,casual,1.646460e+09,1.646460e+09,3,5,5485079.0,5485072.0,-0.117
1467055,0793C9208A64302A,electric_bike,2022-05-30 11:06:29,2022-05-30 11:06:17,Broadway & Waveland Ave,13325,unavailable,0,41.949069,-87.648499,41.950000,-87.650000,casual,1.653889e+09,1.653889e+09,5,30,12913584.0,12913572.0,-0.200
2042411,B3BE8FE661F79405,electric_bike,2022-06-07 16:18:37,2022-06-07 16:07:28,unavailable,0,Clinton St & Washington Blvd,WL-012,41.880000,-87.640000,41.883380,-87.641170,member,1.654599e+09,1.654598e+09,6,7,13623512.0,13622843.0,-11.150
2115909,94B4428CC44303EF,electric_bike,2022-06-07 17:05:24,2022-06-07 16:59:53,Clark St & Berwyn Ave,KA1504000146,unavailable,0,41.978035,-87.668024,41.980000,-87.670000,member,1.654602e+09,1.654601e+09,6,7,13626319.0,13625988.0,-5.517
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5443052,75780B25C9DF4DB1,electric_bike,2022-11-06 01:59:42,2022-11-06 01:04:20,Wilton Ave & Diversey Pkwy,TA1306000014,unavailable,0,41.932236,-87.652662,41.940000,-87.660000,member,1.667680e+09,1.667677e+09,11,6,26704777.0,26701455.0,-55.367
5355885,5FBFC1FD44AD3467,electric_bike,2022-11-06 01:59:42,2022-11-06 01:10:27,Sedgwick St & Webster Ave,13191,Clark St & Elm St,TA1307000039,41.922105,-87.638934,41.902973,-87.631280,casual,1.667680e+09,1.667677e+09,11,6,26704777.0,26701822.0,-49.250
5250222,5B15C685C741E678,classic_bike,2022-11-06 01:59:53,2022-11-06 01:25:35,Clark St & Schiller St,TA1309000024,Clarendon Ave & Leland Ave,TA1307000119,41.907993,-87.631501,41.967968,-87.650001,member,1.667680e+09,1.667678e+09,11,6,26704788.0,26702730.0,-34.300
5367575,9709ACD5F0E8222D,classic_bike,2022-11-14 00:21:59,2022-11-14 00:17:36,Fort Dearborn Dr & 31st St,TA1307000048,MLK Jr Dr & 29th St,TA1307000139,41.838556,-87.608218,41.842052,-87.617000,member,1.668366e+09,1.668365e+09,11,14,27390114.0,27389851.0,-4.383
5220364,71940A5D4B8C92D9,electric_bike,2022-11-18 16:20:53,2022-11-18 16:20:28,unavailable,0,Kingsbury St & Kinzie St,KA1503000043,41.890000,-87.640000,41.889177,-87.638506,member,1.668769e+09,1.668769e+09,11,18,27793248.0,27793223.0,-0.417

In [151]:

df = df.loc[df["ride_time"]>0]

In [152]:
df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,start_time_epoch,end_time_epoch,month,date,start_epoch,end_epoch,ride_time
73479,98D355D9A9852BE9,classic_bike,2022-01-01 00:00:05,2022-01-01 00:01:48,Michigan Ave & 8th St,623,Michigan Ave & 8th St,623,41.872773,-87.623981,41.872773,-87.623981,casual,1.640975e+09,1.640976e+09,1,1,0.0,103.0,1.717
68510,04706CA7F5BD25EE,electric_bike,2022-01-01 00:01:00,2022-01-01 00:04:39,Broadway & Waveland Ave,13325,Broadway & Barry Ave,13137,41.949073,-87.648633,41.937582,-87.644098,casual,1.640975e+09,1.640976e+09,1,1,55.0,274.0,3.650
64490,42178E850B92597A,electric_bike,2022-01-01 00:01:16,2022-01-01 00:32:14,Clark St & Ida B Wells Dr,TA1305000009,Clark St & Ida B Wells Dr,TA1305000009,41.875919,-87.631194,41.875933,-87.630585,casual,1.640975e+09,1.640977e+09,1,1,71.0,1929.0,30.967
73485,6B93C46E8F5B114C,classic_bike,2022-01-01 00:02:14,2022-01-01 00:31:07,Michigan Ave & 8th St,623,Michigan Ave & 8th St,623,41.872773,-87.623981,41.872773,-87.623981,casual,1.640976e+09,1.640977e+09,1,1,129.0,1862.0,28.883
73478,466943353EAC8022,classic_bike,2022-01-01 00:02:35,2022-01-01 00:31:04,Michigan Ave & 8th St,623,Michigan Ave & 8th St,623,41.872773,-87.623981,41.872773,-87.623981,casual,1.640976e+09,1.640977e+09,1,1,150.0,1859.0,28.483
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5490051,78090C14B6003F5D,classic_bike,2022-12-31 23:57:18,2023-01-01 00:21:40,Wabash Ave & 9th St,TA1309000010,Clark St & Elm St,TA1307000039,41.870769,-87.625734,41.902973,-87.631280,member,1.672511e+09,1.672513e+09,12,31,31535833.0,31537295.0,24.367
5652875,207B82AF834747FD,electric_bike,2022-12-31 23:58:01,2023-01-01 00:06:40,Damen Ave & Thomas St (Augusta Blvd),TA1307000070,Troy St & North Ave,15653,41.901250,-87.677353,41.909769,-87.705280,casual,1.672511e+09,1.672512e+09,12,31,31535876.0,31536395.0,8.650
5634763,390512AD1B791E95,classic_bike,2022-12-31 23:58:41,2023-01-01 00:16:53,Indiana Ave & Roosevelt Rd,SL-005,Indiana Ave & Roosevelt Rd,SL-005,41.867888,-87.623041,41.867888,-87.623041,casual,1.672511e+09,1.672512e+09,12,31,31535916.0,31537008.0,18.200
5634907,017486468322F08A,electric_bike,2022-12-31 23:59:01,2023-01-01 00:16:50,Indiana Ave & Roosevelt Rd,SL-005,Indiana Ave & Roosevelt Rd,SL-005,41.868109,-87.623071,41.867888,-87.623041,member,1.672511e+09,1.672512e+09,12,31,31535936.0,31537005.0,17.817
5582591,C4F7BB2F10637EA0,electric_bike,2022-12-31 23:59:26,2023-01-01 00:01:54,Drake Ave & Addison St,KA1504000142,Monticello Ave & Irving Park Rd,KA1504000139,41.947421,-87.717623,41.954005,-87.719128,member,1.672511e+09,1.672512e+09,12,31,31535961.0,31536109.0,2.467